---
deployment:
  tasks:
    - export REPOPATH=/home/smertnik/repositories/estart_v1/*
    - export SITEPATH=/home/smertnik/estart.smertnik.site/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
